aliases = [ "es2025" ]
dependencies = [
	"_ESAbstract.CreateMethodProperty",
	"_ESAbstract.CreateNumericRangeIterator",
	"Iterator",
]
spec = "https://tc39.es/proposal-iterator-helpers/#sec-iterator.range"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator/range"

# TODO
[browsers]
android = "*"
bb = "*"
chrome = "*"
edge = "*"
edge_mob = "*"
firefox = "*"
firefox_mob = "*"
ie = "*"
ie_mob = "*"
opera = "*"
op_mob = "*"
op_mini = "*"
safari = "*"
ios_saf = "*"
samsung_mob = "*"
