dependencies = [ ]
notes = [ ]
spec = "http://www.w3.org/TR/screen-orientation/"
docs = "https://developer.mozilla.org/en-US/docs/Web/API/Screen/orientation"

[browsers]
android = "<5"
bb = "*"
chrome = "<49"
edge = "*"
edge_mob = "*"
firefox = "<43"
firefox_mob = "<43"
ie = ">=9"
ie_mob = "*"
opera = "<25"
op_mob = "<36"
safari = "<16.4"
ios_saf = "<16.4"
samsung_mob = "<5.0"
