aliases = [ "es2024" ]
dependencies = [
	"_ESAbstract.CreateDataPropertyOrThrow",
	"_ESAbstract.CreateMethodProperty",
	"_ESAbstract.IsConstructor",
	"Promise",
]
license = "MIT"
spec = "https://tc39.es/ecma262/#sec-promise.withResolvers"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/withResolvers"

[browsers]
android = "*"
bb = "*"
chrome = "<119"
edge = "*"
edge_mob = "*"
firefox = "<121"
firefox_mob = "<121"
ie = "*"
ie_mob = "*"
opera = "<105"
op_mob = "<79"
op_mini = "*"
safari = "<17.4"
ios_saf = "<17.4"
samsung_mob = "*"
