aliases = [
	"Int8Array",
	"Uint8Array",
	"Uint8ClampedArray",
	"Int16Array",
	"Uint16Array",
	"Int32Array",
	"Uint32Array",
	"Float32Array",
	"Float64Array",
	"DataView"
]
license = "MIT"
repo = "https://github.com/inexorabletash/polyfill"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray"

[browsers]
android = "*"
bb = "*"
chrome = "<32"
edge = "<14"
edge_mob = "<14"
firefox = "<44"
firefox_mob = "<44"
ie = "*"
ie_mob = "*"
opera = "<19"
op_mob = "<19"
op_mini = "*"
safari = "<7.0"
ios_saf = "<7.0"
samsung_mob = "<2.0"

[install]
module = "js-polyfills"
paths = [ "typedarray.js" ]
postinstall = "update.task.js"
