// Command polyfills-update-browser-list refreshes the BrowserStack browser
// matrix, replacing `npm run update-browserstack-list`.
//
// It writes two files:
//
//	test/polyfills/browserstackBrowsers.toml - every browser, version, device
//	                                          and platform BrowserStack offers.
//	test/polyfills/browsers.toml              - the curated "family/version"
//	                                          entries actually under test.
//
// Unlike the JavaScript script it replaced, browsers.toml keeps the existing
// curation: entries a maintainer has commented out stay commented out, and
// newly offered browsers are added uncommented and ready to be reviewed.
package main

import (
	"context"
	"flag"
	"fmt"
	"log"
	"os"
	"sort"
	"strings"

	"github.com/Masterminds/semver/v3"
	"github.com/mrhenry/polyfill-library/scripts/browserstack"
)

const header = "# This file is automatically generated via `npm run update-browserstack-list`\n"

func main() {
	var (
		browsersPath string
		stackPath    string
	)

	flag.StringVar(&browsersPath, "browsers", "test/polyfills/browsers.toml", "path to the curated browser list")
	flag.StringVar(&stackPath, "browserstack-browsers", "test/polyfills/browserstackBrowsers.toml", "path to the generated BrowserStack list")

	flag.Parse()

	if err := run(browsersPath, stackPath); err != nil {
		log.Println("error:", err)
		os.Exit(1)
	}
}

func run(browsersPath, stackPath string) error {
	credentials := browserstack.Credentials{
		UserName:  os.Getenv("BROWSERSTACK_USERNAME"),
		AccessKey: os.Getenv("BROWSERSTACK_ACCESS_KEY"),
	}
	if !credentials.Valid() {
		return fmt.Errorf("BROWSERSTACK_USERNAME and BROWSERSTACK_ACCESS_KEY must be set in the environment")
	}

	ctx := context.Background()

	client := browserstack.New(browserstack.Config{Credentials: credentials})

	browsers, err := client.Browsers(ctx)
	if err != nil {
		return err
	}

	// Non Safari browsers on iOS cannot be targeted by the polyfill library,
	// because every iOS browser is driven through Safari.
	filtered := browsers[:0]
	for _, b := range browsers {
		if strings.EqualFold(b.OS, "ios") && !strings.EqualFold(b.Browser, "iphone") && !strings.EqualFold(b.Browser, "ipad") {
			continue
		}

		filtered = append(filtered, b)
	}
	browsers = filtered

	sort.SliceStable(browsers, func(i, j int) bool {
		return browserLess(browsers[i], browsers[j])
	})

	if err := os.WriteFile(stackPath, []byte(renderBrowserStackTOML(browsers)), 0o644); err != nil {
		return err
	}

	log.Printf("wrote %s (%d browsers)", stackPath, len(browsers))

	entries := uniqueEntries(browsers)
	sort.SliceStable(entries, func(i, j int) bool {
		return entryLess(entries[i], entries[j])
	})

	// Preserve the curation a maintainer wrote by hand: which entries are
	// commented out, and the notes beside them.
	states := readEntryStates(browsersPath)

	rendered := renderBrowsersTOML(entries, states)

	if err := os.WriteFile(browsersPath, []byte(rendered), 0o644); err != nil {
		return err
	}

	var enabled, skipped int

	for _, entry := range entries {
		if states[entry].disabled {
			skipped++

			continue
		}

		enabled++
	}

	log.Printf("wrote %s (%d entries: %d under test, %d commented out)", browsersPath, len(entries), enabled, skipped)

	return nil
}

// browserLess reproduces the sort in tasks/updatebrowserstacklist.js.
//
// Desktop browser versions ascend; Windows and OS X platform versions
// descend, so the newest platform is listed first for each browser version.
func browserLess(a, b browserstack.Browser) bool {
	if a.Browser != b.Browser {
		return localeLess(a.Browser, b.Browser)
	}

	if a.BrowserVersion != "" && b.BrowserVersion != "" && a.BrowserVersion != b.BrowserVersion {
		return versionLess(a.BrowserVersion, b.BrowserVersion)
	}

	if a.OS != b.OS {
		return localeLess(a.OS, b.OS)
	}

	if a.OSVersion != b.OSVersion && a.OSVersion != "" && b.OSVersion != "" {
		descending := strings.EqualFold(a.OS, "windows") || strings.EqualFold(a.OS, "os x")

		if descending {
			return versionLess(b.OSVersion, a.OSVersion)
		}

		return versionLess(a.OSVersion, b.OSVersion)
	}

	return localeLess(a.Device, b.Device)
}

// entryLess sorts "family/version" entries by family, then ascending version.
func entryLess(a, b string) bool {
	aFamily, aVersion, _ := strings.Cut(a, "/")
	bFamily, bVersion, _ := strings.Cut(b, "/")

	if aFamily != bFamily {
		return localeLess(aFamily, bFamily)
	}

	if aVersion != bVersion {
		return versionLess(aVersion, bVersion)
	}

	return false
}

// versionLess compares the leading numeric part of two version strings,
// falling back to a string comparison, matching semver.coerce plus
// semver.compare.
func versionLess(a, b string) bool {
	ca, oka := coerceVersion(a)
	cb, okb := coerceVersion(b)

	if oka && okb {
		return ca.LessThan(cb)
	}

	if oka != okb {
		return oka
	}

	return localeLess(a, b)
}

func coerceVersion(v string) (*semver.Version, bool) {
	parts := strings.SplitN(v, ".", 3)

	out := make([]string, 0, 3)

	for _, part := range parts {
		digits := leadingDigits(part)
		if digits == "" {
			break
		}

		out = append(out, digits)
	}

	if len(out) == 0 {
		return nil, false
	}

	for len(out) < 3 {
		out = append(out, "0")
	}

	parsed, err := semver.NewVersion(strings.Join(out, "."))
	if err != nil {
		return nil, false
	}

	return parsed, true
}

func leadingDigits(s string) string {
	end := 0
	for end < len(s) && s[end] >= '0' && s[end] <= '9' {
		end++
	}

	return s[:end]
}

// localeLess approximates String.prototype.localeCompare for the ASCII names
// BrowserStack uses.
func localeLess(a, b string) bool {
	return a < b
}

// uniqueEntries reduces the browser list to one "family/version" entry per
// browser version, using os/os_version for real devices.
func uniqueEntries(browsers []browserstack.Browser) []string {
	seen := map[string]bool{}

	var out []string

	for _, b := range browsers {
		var entry string
		if b.BrowserVersion != "" {
			entry = b.Browser + "/" + b.BrowserVersion
		} else {
			entry = b.OS + "/" + b.OSVersion
		}

		if seen[entry] {
			continue
		}

		seen[entry] = true

		out = append(out, entry)
	}

	return out
}

// entryState is how an entry appears in the existing browsers.toml.
type entryState struct {
	disabled bool
	comment  string
}

// readEntryStates reads the existing browsers.toml and records, for every
// entry, whether it is commented out and any trailing comment. Both are
// curation a maintainer wrote by hand, so both are preserved on rewrite.
func readEntryStates(path string) map[string]entryState {
	raw, err := os.ReadFile(path)
	if err != nil {
		return map[string]entryState{}
	}

	states := map[string]entryState{}

	inBrowsersArray := false

	for _, line := range strings.Split(string(raw), "\n") {
		trimmed := strings.TrimSpace(line)

		switch {
		case strings.HasPrefix(trimmed, "browsers"):
			inBrowsersArray = true
		case strings.HasPrefix(trimmed, "]"):
			inBrowsersArray = false
		case inBrowsersArray && strings.HasPrefix(trimmed, "#"):
			if entry, comment, ok := parseEntry(trimmed); ok {
				states[entry] = entryState{disabled: true, comment: comment}
			}
		case inBrowsersArray && trimmed != "":
			if entry, comment, ok := parseEntry(trimmed); ok {
				states[entry] = entryState{comment: comment}
			}
		}
	}

	return states
}

// parseEntry pulls the quoted string and any trailing comment out of a
// browsers.toml list line, which may be commented out.
func parseEntry(line string) (entry string, comment string, ok bool) {
	body := strings.TrimSpace(line)

	disabled := strings.HasPrefix(body, "#")
	if disabled {
		body = strings.TrimSpace(strings.TrimPrefix(body, "#"))
	}

	start := strings.Index(body, `"`)
	end := strings.LastIndex(body, `"`)
	if start == -1 || end <= start {
		return "", "", false
	}

	entry = body[start+1 : end]

	// A trailing comment is kept whether or not the entry is commented out, so
	// a maintainer's note beside a disabled entry survives regeneration.
	if hash := strings.Index(body[end+1:], "#"); hash != -1 {
		comment = strings.TrimSpace(body[end+1+hash+1:])
	}

	return entry, comment, true
}

// renderBrowsersTOML writes browsers.toml, keeping entries a maintainer
// commented out commented out, and keeping their trailing notes.
func renderBrowsersTOML(entries []string, states map[string]entryState) string {
	var b strings.Builder

	b.WriteString(header)
	b.WriteString("browsers = [\n")

	for _, entry := range entries {
		state := states[entry]
		comment := state.comment

		if comment != "" {
			comment = " # " + comment
		}

		if state.disabled {
			fmt.Fprintf(&b, "  # %q,%s\n", entry, comment)

			continue
		}

		fmt.Fprintf(&b, "  %q,%s\n", entry, comment)
	}

	b.WriteString("]\n")

	return b.String()
}

// renderBrowserStackTOML writes the full browserstackBrowsers.toml, matching
// the field order @iarna/toml produced.
func renderBrowserStackTOML(browsers []browserstack.Browser) string {
	var b strings.Builder

	b.WriteString(header)

	for _, entry := range browsers {
		b.WriteString("[[browsers]]\n")
		fmt.Fprintf(&b, "os = %q\n", entry.OS)

		if entry.OSVersion != "" {
			fmt.Fprintf(&b, "os_version = %q\n", entry.OSVersion)
		}

		if entry.Browser != "" {
			fmt.Fprintf(&b, "browser = %q\n", entry.Browser)
		}

		if entry.BrowserVersion != "" {
			fmt.Fprintf(&b, "browser_version = %q\n", entry.BrowserVersion)
		}

		if entry.Device != "" {
			fmt.Fprintf(&b, "device = %q\n", entry.Device)
		}

		if entry.RealMobile {
			b.WriteString("real_mobile = true\n")
		}

		b.WriteString("\n")
	}

	return b.String()
}
