dependencies = [
	"Array.prototype.@@iterator",
	"Iterator",
	"Map",
	"Set",
	"String.prototype.@@iterator",
	"Symbol.iterator",
]
notes = [ ]
license = "MIT"
repo = "https://github.com/es-shims/iterator-helpers"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator#iterator_helpers"

[browsers]
android = "*"
bb = "*"
chrome = "*"
edge = "*"
edge_mob = "*"
firefox = "*"
firefox_mob = "*"
ie = "*"
ie_mob = "*"
opera = "*"
op_mob = "*"
op_mini = "*"
safari = "*"
ios_saf = "*"
samsung_mob = "*"

[install]
module = "es-iterator-helpers"
postinstall = "update.task.js"
clean = [ "polyfill.js" ]
