aliases = [ "es2025" ]
dependencies = [
	"_ESAbstract.CreateMethodProperty",
	"_ESAbstract.GetIterator",
	"_ESAbstract.GetSetRecord",
	"_ESAbstract.IteratorClose",
	"_ESAbstract.IteratorStepValue",
	"_ESAbstract.NormalCompletion",
	"Set",
]
license = "MIT"
spec = "https://tc39.es/ecma262/#sec-set.prototype.issupersetof"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/isSupersetOf"

[browsers]
android = "*"
bb = "*"
chrome = "<122"
edge = "*"
firefox = "<127"
firefox_mob = "<127"
ie = "*"
ie_mob = "*"
opera = "<108"
op_mob = "<81"
op_mini = "*"
safari = "<17.0"
ios_saf = "<17.0"
samsung_mob = "*"
