aliases = [ "es6", "es2015" ]
dependencies = [
	"_ESAbstract.CreateMethodProperty",
	"Iterator",
	"Symbol.iterator",
]
license = "MIT"
spec = "https://tc39.es/ecma262/#sec-iterator.prototype-%symbol.iterator%"
docs = "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator/Symbol.iterator"

[browsers]
android = "<5.1"
bb = "10 - *"
chrome = "<49"
edge = "<13"
edge_mob = "<13"
firefox = "<17"
firefox_mob = "<17"
ie = "*"
ie_mob = "*"
opera = "<37"
op_mob = "<37"
safari = "<9.0"
ios_saf = "<9.0"
samsung_mob = "<5.0"
